name: tracker_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.4.4
  go_router: ^14.2.3
  fpdart: ^1.1.0
  dio: ^5.3.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.2.1
  path_provider: ^2.1.1
  hive: ^2.2.3
  flutter_dotenv: ^5.1.0
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  firebase_messaging: ^15.0.4
  cloud_firestore: ^5.2.1
  google_maps_flutter: ^2.9.0
  flutter_config: ^2.0.2
  geolocator: ^12.0.0
  logging: ^1.2.0
  connectivity_plus: ^6.0.5
   


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  riverpod_generator: ^2.3.5
  riverpod_lint: ^2.3.2
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  
  # assets:
    # - .env
    # - images/a_dot_burr.jpeg
    # - images/a_dot_ham.jpeg

  # fonts:
  #   - family: PlaypenSans
  #     fonts:
  #       - asset: assets/fonts/PlaypenSans-Regular.ttf

  #       - asset: assets/fonts/PlaypenSans-Bold.ttf
  #         weight: 700

  #       - asset: assets/fonts/PlaypenSans-SemiBold.ttf
  #         weight: 400
